language: rust
dist: precise
before_install:
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-precise-3.8 main'
 - sudo apt-get -qq update
 - sudo apt-get -y install llvm llvm-3.8-dev
