language: rust
dist: trusty
before_install:
 - sudo rm -rf /usr/local/clang-*
 - sudo apt-get purge llvm-3.4
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - sudo add-apt-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
 - sudo apt-get -qq update
 - sudo apt-get -y --force-yes install llvm llvm-3.8-dev
 - which llvm-config
 - ls -l `which llvm-config`
 - dpkg -S `which llvm-config`
