language: rust
dist: trusty
before_install:
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
 - sudo apt-get -qq update
 - sudo aptitude install -y llvm-3.8-dev
